name: NeuronTools
options:
  bundleIdPrefix: com.wvabrinskas
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  Neuron:
    url: https://github.com/wvabrinskas/Neuron.git
    branch: develop
  NumSwift:
    url: https://github.com/wvabrinskas/NumSwift.git
    branch: main
  Logger:
    url: https://github.com/wvabrinskas/Logger.git
    from: "1.0.6"
  swift-numerics:
    url: https://github.com/apple/swift-numerics
    from: "1.0.0"

targets:
  NeuronTools:
    type: application
    platform: macOS
    sources:
      - Sources/NeuronTools
    dependencies:
      - package: Neuron
      - package: NumSwift
      - package: Logger
      - package: swift-numerics
        product: Numerics
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wvabrinskas.NeuronTools
        PRODUCT_NAME: NeuronTools
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.10"
    info:
      path: Sources/NeuronTools/Info.plist
      properties:
        CFBundleName: NeuronTools
        CFBundleDisplayName: NeuronTools
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSMainStoryboardFile: ""
